name: "Infrastructure CI/CD"

on:
  push:
    branches:
      - "main"

jobs:
  run:
    name: "Terraform infrastructure Pipeline"
    permissions:
      id-token: write
      contents: read
    runs-on: "ubuntu-latest"
    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: "Checkout"
        uses: "actions/checkout@v3"

      # Authenticate to GCP using Workload Identity Federation
      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
          create_credentials_file: true

      # Install the latest version of Terraform CLI
      - name: "Setup Terraform"
        uses: "hashicorp/setup-terraform@v1"
      
      # Initializes Terraform
      - name: "Terraform Init"
        run: "terraform init"

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: "Terraform Format"
        run: "terraform fmt -check"

      # Generates an execution plan for Terraform
      - name: "Terraform Plan"
        run: "terraform plan -input=false"

      # Builds or changes infrastructure according to Terraform configuration files
      - name: "Terraform Apply"
        run: "terraform apply -auto-approve -input=false"
